### PR TITLE
Fix empty version range crash

### PR DESCRIPTION
**Pull request by janniclas**
This PR address the issue reported in https://github.com/nexB/vulnerablecode/issues/1214 . 

I'm not familiar with either this project nor python, so I'm unsure if this is a good solution. However, it solved the issue I described in the linked ticket. Feedback welcome!

### CODE REVIEW

**Comment by TG1999** [comment]
@janniclas thanks for this PR, if you can add some tests to highlight the issues which are fixed by this PR it would be really helpful.

**Comment by janniclas** [comment]
Sure, I'll look into it soonish

**Comment by janniclas** [comment]
@TG1999 I added a test case based upon the original input I got when running the vulnerabilities.importers.apache_httpd.ApacheHTTPDImporter .

**Comment by TG1999** [comment]
@janniclas sorry for late reply, please resolve the merge conflicts : )

**Pull request closed without merging**
